services:
  - type: web
    name: svexam-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
