// סקריפט חד-פעמי למילוי 100 סרטים מובחרים. הרצה: node src/seed.js
import 'dotenv/config';
import mongoose from 'mongoose';
import Movie from './models/Movie.js';

const movies = [
  { title: 'The Shawshank Redemption', year: 1994, genre: 'Drama', description: 'A banker forms hope and friendship over years in prison.' },
  { title: 'The Godfather', year: 1972, genre: 'Crime', description: 'A mafia dynasty passes power from father to reluctant son.' },
  { title: 'The Dark Knight', year: 2008, genre: 'Action', description: 'Batman faces the Joker, chaos incarnate, in Gotham City.' },
  { title: 'The Godfather Part II', year: 1974, genre: 'Crime', description: 'The Corleone saga of rise and moral decay continues.' },
  { title: '12 Angry Men', year: 1957, genre: 'Drama', description: 'One juror challenges eleven others to reconsider a verdict.' },
  { title: "Schindler's List", year: 1993, genre: 'Drama', description: 'A businessman saves Jews during the Holocaust.' },
  { title: 'The Lord of the Rings: The Return of the King', year: 2003, genre: 'Fantasy', description: 'The final stand against Sauron for Middle-earth.' },
  { title: 'Pulp Fiction', year: 1994, genre: 'Crime', description: 'Interwoven LA crime stories told out of order.' },
  { title: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001, genre: 'Fantasy', description: 'A hobbit begins a quest to destroy the One Ring.' },
  { title: 'The Good, the Bad and the Ugly', year: 1966, genre: 'Western', description: 'Three gunmen race for buried Confederate gold.' },
  { title: 'Forrest Gump', year: 1994, genre: 'Drama', description: 'A simple man unknowingly shapes decades of history.' },
  { title: 'Fight Club', year: 1999, genre: 'Drama', description: 'An insomniac forms an underground fight club.' },
  { title: 'Inception', year: 2010, genre: 'Sci-Fi', description: 'Thieves plant an idea deep inside a target dream.' },
  { title: 'The Lord of the Rings: The Two Towers', year: 2002, genre: 'Fantasy', description: 'The fellowship fights as war spreads over Middle-earth.' },
  { title: 'Star Wars: The Empire Strikes Back', year: 1980, genre: 'Sci-Fi', description: 'The Rebels reel as Vader reveals a dark truth.' },
  { title: 'The Matrix', year: 1999, genre: 'Sci-Fi', description: 'A hacker learns reality is a simulated prison.' },
  { title: 'Goodfellas', year: 1990, genre: 'Crime', description: 'The rise and fall of a mob associate.' },
  { title: "One Flew Over the Cuckoo's Nest", year: 1975, genre: 'Drama', description: 'A rebel shakes up a strict psychiatric ward.' },
  { title: 'Se7en', year: 1995, genre: 'Thriller', description: 'Two detectives hunt a killer using the deadly sins.' },
  { title: 'Seven Samurai', year: 1954, genre: 'Action', description: 'Warriors defend a village from bandits.' },
  { title: "It's a Wonderful Life", year: 1946, genre: 'Drama', description: 'An angel shows a man the value of his life.' },
  { title: 'The Silence of the Lambs', year: 1991, genre: 'Thriller', description: "An agent seeks a killer with a cannibal's help." },
  { title: 'Saving Private Ryan', year: 1998, genre: 'War', description: 'Soldiers search for one paratrooper in WWII.' },
  { title: 'City of God', year: 2002, genre: 'Crime', description: 'Two boys take different paths in a Rio slum.' },
  { title: 'Life Is Beautiful', year: 1997, genre: 'Drama', description: 'A father shields his son inside a concentration camp.' },
  { title: 'The Green Mile', year: 1999, genre: 'Drama', description: 'Guards meet a gentle inmate with a strange gift.' },
  { title: 'Interstellar', year: 2014, genre: 'Sci-Fi', description: 'Explorers seek a new home beyond a wormhole.' },
  { title: 'Star Wars', year: 1977, genre: 'Sci-Fi', description: 'A farm boy joins the rebellion against the Empire.' },
  { title: 'Terminator 2: Judgment Day', year: 1991, genre: 'Action', description: 'A reprogrammed cyborg protects a future leader.' },
  { title: 'Back to the Future', year: 1985, genre: 'Sci-Fi', description: 'A teen travels to 1955 in a DeLorean time machine.' },
  { title: 'Spirited Away', year: 2001, genre: 'Animation', description: 'A girl works in a spirit bathhouse to save her parents.' },
  { title: 'The Pianist', year: 2002, genre: 'Drama', description: 'A musician survives the Warsaw ghetto in WWII.' },
  { title: 'Psycho', year: 1960, genre: 'Horror', description: 'A motel hides a deadly secret behind its owner.' },
  { title: 'Parasite', year: 2019, genre: 'Thriller', description: 'A poor family schemes into a wealthy household.' },
  { title: 'Gladiator', year: 2000, genre: 'Action', description: 'A betrayed general fights for revenge in the arena.' },
  { title: 'The Lion King', year: 1994, genre: 'Animation', description: 'A young lion reclaims his throne after tragedy.' },
  { title: 'Léon: The Professional', year: 1994, genre: 'Action', description: 'A hitman protects an orphaned girl seeking revenge.' },
  { title: 'The Departed', year: 2006, genre: 'Crime', description: 'A mole and an undercover cop hunt each other.' },
  { title: 'American History X', year: 1998, genre: 'Drama', description: 'A reformed skinhead tries to save his brother.' },
  { title: 'Whiplash', year: 2014, genre: 'Drama', description: 'A drummer is pushed to genius by a brutal teacher.' },
  { title: 'The Prestige', year: 2006, genre: 'Drama', description: 'Rival magicians wage a deadly battle of tricks.' },
  { title: 'Casablanca', year: 1942, genre: 'Romance', description: 'A cynic must choose love or duty in wartime.' },
  { title: 'The Intouchables', year: 2011, genre: 'Comedy', description: 'A rich quadriplegic bonds with his street caretaker.' },
  { title: 'Modern Times', year: 1936, genre: 'Comedy', description: 'A tramp struggles in the industrial age.' },
  { title: 'Once Upon a Time in the West', year: 1968, genre: 'Western', description: 'A mysterious gunman avenges a brutal killing.' },
  { title: 'Grave of the Fireflies', year: 1988, genre: 'Animation', description: 'Two siblings struggle to survive wartime Japan.' },
  { title: 'Rear Window', year: 1954, genre: 'Thriller', description: 'A man suspects a neighbor of murder.' },
  { title: 'Alien', year: 1979, genre: 'Sci-Fi', description: 'A crew is hunted by a creature aboard their ship.' },
  { title: 'City Lights', year: 1931, genre: 'Romance', description: 'A tramp falls for a blind flower girl.' },
  { title: 'Cinema Paradiso', year: 1988, genre: 'Drama', description: 'A director recalls his boyhood love of film.' },
  { title: 'Apocalypse Now', year: 1979, genre: 'War', description: 'An officer journeys upriver to find a rogue colonel.' },
  { title: 'Memento', year: 2000, genre: 'Thriller', description: "A man with no memory hunts his wife's killer." },
  { title: 'Raiders of the Lost Ark', year: 1981, genre: 'Action', description: 'Indiana Jones races Nazis for the Ark.' },
  { title: 'Django Unchained', year: 2012, genre: 'Western', description: 'A freed slave hunts bounties to rescue his wife.' },
  { title: 'WALL·E', year: 2008, genre: 'Animation', description: 'A lonely robot finds love and saves humanity.' },
  { title: 'The Lives of Others', year: 2006, genre: 'Drama', description: 'A Stasi agent is moved by those he spies on.' },
  { title: 'Sunset Boulevard', year: 1950, genre: 'Drama', description: 'A faded star clings to a fading Hollywood dream.' },
  { title: 'Paths of Glory', year: 1957, genre: 'War', description: 'An officer defends soldiers from unjust execution.' },
  { title: 'The Shining', year: 1980, genre: 'Horror', description: 'A caretaker family unravels in a haunted hotel.' },
  { title: 'The Great Dictator', year: 1940, genre: 'Comedy', description: 'A barber is mistaken for a ruthless dictator.' },
  { title: 'Witness for the Prosecution', year: 1957, genre: 'Drama', description: 'A barrister defends a man in a twisty murder trial.' },
  { title: 'Aliens', year: 1986, genre: 'Sci-Fi', description: 'Marines battle a swarm of deadly creatures.' },
  { title: 'Spider-Man: Into the Spider-Verse', year: 2018, genre: 'Animation', description: 'A teen joins Spider-heroes across dimensions.' },
  { title: 'Dr. Strangelove', year: 1964, genre: 'Comedy', description: 'A nuclear mishap spirals into dark farce.' },
  { title: 'Oldboy', year: 2003, genre: 'Thriller', description: 'A man seeks revenge after 15 years imprisoned.' },
  { title: 'Coco', year: 2017, genre: 'Animation', description: 'A boy journeys to the Land of the Dead.' },
  { title: 'Toy Story', year: 1995, genre: 'Animation', description: 'Toys come to life and learn to share a boy.' },
  { title: 'Amadeus', year: 1984, genre: 'Drama', description: "A jealous composer is haunted by Mozart's genius." },
  { title: 'Avengers: Infinity War', year: 2018, genre: 'Action', description: 'Heroes unite to stop Thanos from erasing life.' },
  { title: 'Braveheart', year: 1995, genre: 'War', description: 'A Scot leads a rebellion for freedom.' },
  { title: 'Inglourious Basterds', year: 2009, genre: 'War', description: 'A plot to kill Nazi leaders in occupied France.' },
  { title: 'Das Boot', year: 1981, genre: 'War', description: 'A German U-boat crew faces the terror of the sea.' },
  { title: 'Princess Mononoke', year: 1997, genre: 'Animation', description: 'A prince is caught between humans and forest gods.' },
  { title: 'Once Upon a Time in America', year: 1984, genre: 'Crime', description: 'Friends rise and fall through decades of crime.' },
  { title: 'Good Will Hunting', year: 1997, genre: 'Drama', description: 'A gifted janitor confronts his past with a therapist.' },
  { title: 'Requiem for a Dream', year: 2000, genre: 'Drama', description: 'Four lives spiral into addiction and ruin.' },
  { title: 'Toy Story 3', year: 2010, genre: 'Animation', description: 'The toys face an uncertain future as Andy grows up.' },
  { title: 'Star Wars: Return of the Jedi', year: 1983, genre: 'Sci-Fi', description: 'The Rebels make a final strike against the Empire.' },
  { title: 'Reservoir Dogs', year: 1992, genre: 'Crime', description: 'A heist goes wrong and suspicion turns deadly.' },
  { title: '2001: A Space Odyssey', year: 1968, genre: 'Sci-Fi', description: 'A voyage to Jupiter confronts artificial intelligence.' },
  { title: 'Citizen Kane', year: 1941, genre: 'Drama', description: "A reporter probes a tycoon's mysterious last word." },
  { title: 'M', year: 1931, genre: 'Crime', description: 'A city hunts a child murderer in its streets.' },
  { title: 'The Hunt', year: 2012, genre: 'Drama', description: 'A teacher is falsely accused and shunned.' },
  { title: 'Vertigo', year: 1958, genre: 'Thriller', description: "A detective's obsession spirals into illusion." },
  { title: 'North by Northwest', year: 1959, genre: 'Thriller', description: 'A man is chased after a case of mistaken identity.' },
  { title: 'Eternal Sunshine of the Spotless Mind', year: 2004, genre: 'Romance', description: 'A couple erase each other from their memories.' },
  { title: 'A Clockwork Orange', year: 1971, genre: 'Sci-Fi', description: 'A violent youth undergoes radical reform therapy.' },
  { title: 'Lawrence of Arabia', year: 1962, genre: 'Adventure', description: 'A British officer unites Arab tribes in WWI.' },
  { title: 'Taxi Driver', year: 1976, genre: 'Drama', description: 'A lonely cabbie descends into violent obsession.' },
  { title: 'Double Indemnity', year: 1944, genre: 'Crime', description: 'An agent and a wife plot a deadly insurance scam.' },
  { title: 'Bicycle Thieves', year: 1948, genre: 'Drama', description: 'A poor man searches Rome for his stolen bike.' },
  { title: 'Snatch', year: 2000, genre: 'Crime', description: 'A stolen diamond entangles boxers and crooks.' },
  { title: 'Full Metal Jacket', year: 1987, genre: 'War', description: 'Marines are forged in boot camp and Vietnam.' },
  { title: 'The Sting', year: 1973, genre: 'Comedy', description: 'Two grifters con a mob boss in the 1930s.' },
  { title: 'The Apartment', year: 1960, genre: 'Romance', description: 'A clerk lends his flat to climb the corporate ladder.' },
  { title: 'Metropolis', year: 1927, genre: 'Sci-Fi', description: 'A worker uprising rocks a futuristic divided city.' },
  { title: 'Scarface', year: 1983, genre: 'Crime', description: 'A refugee builds and loses a cocaine empire.' },
  { title: 'Up', year: 2009, genre: 'Animation', description: 'An old man flies his house to a lost paradise.' },
  { title: 'Heat', year: 1995, genre: 'Crime', description: 'A detective and a thief mirror each other in LA.' },
  { title: 'Jurassic Park', year: 1993, genre: 'Adventure', description: 'A dinosaur theme park spirals into chaos.' },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  await Movie.deleteMany({});
  await Movie.insertMany(movies);
  console.log(`✅ Seeded ${movies.length} movies`);
  await mongoose.disconnect();
}

seed();
